"""Create issues command - main logic."""

import json
import logging
from pathlib import Path

import click

from . import github_api, pitfalls

logger = logging.getLogger(__name__)


def detect_platform(url: str) -> str:
    """Detect platform from URL."""
    if "github.com" in url:
        return "github"
    elif "gitlab" in url.lower():
        return "gitlab"
    else:
        raise ValueError(f"Unknown platform for URL: {url}")


@click.command()
@click.option(
    "--pitfalls-output-dir",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="Directory containing pitfalls JSON-LD files from metacheck analysis.",
)
@click.option(
    "--issues-dir",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=Path.cwd(),
    help="Directory to save issue bodies and reports.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Simulate issue creation without actually posting to repositories.",
)
@click.option(
    "--log-level",
    type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"], case_sensitive=False),
    default="INFO",
    help="Logging level.",
)
def create_issues_command(
    pitfalls_output_dir: Path,
    issues_dir: Path,
    dry_run: bool,
    log_level: str,
):
    """
    Create issues in repositories based on metadata analysis results.

    This command processes pitfalls files generated by the metacheck tool
    and creates corresponding issues in the analyzed repositories.
    """
    # Setup logging
    logging.basicConfig(
        level=log_level.upper(),
        format="%(levelname)s: %(message)s",
    )

    # Create output directory
    issues_dir.mkdir(parents=True, exist_ok=True)

    # Initialize API clients
    github = github_api.GitHubAPI(dry_run=dry_run)
    # gitlab = gitlab_api.GitLabAPI(dry_run=dry_run)

    mode = "DRY RUN" if dry_run else "PRODUCTION"
    click.echo(f"\n{'=' * 60}")
    click.echo(f"Creating issues [{mode}]")
    click.echo(f"{'=' * 60}\n")

    # Find pitfalls files
    pitfalls_files = sorted(pitfalls_output_dir.glob("*.jsonld"))
    if not pitfalls_files:
        click.echo(f"No pitfalls files found in {pitfalls_output_dir}", err=True)
        return

    click.echo(f"Found {len(pitfalls_files)} pitfalls files to process\n")

    # Process each file
    created = []
    failed = []

    for i, file_path in enumerate(pitfalls_files, 1):
        click.echo(f"[{i}/{len(pitfalls_files)}] Processing: {file_path.name}")

        try:
            # Load pitfalls
            data = pitfalls.load_pitfalls(file_path)
            repo_url = pitfalls.get_repository_url(data)
            click.echo(f"  Repository: {repo_url}")

            # Generate issue content
            report = pitfalls.format_report(repo_url, data)
            body = pitfalls.create_issue_body(report)

            # Save issue body
            body_file = issues_dir / f"issue_body_{file_path.stem}.md"
            with open(body_file, "w", encoding="utf-8") as f:
                f.write(body)
            click.echo(f"  Issue body saved to: {body_file}")

            # Create issue
            platform = detect_platform(repo_url)
            title = "Automated Metadata Quality Report from CodeMetaSoft"

            if platform == "github":
                issue_url = github.create_issue(repo_url, title, body)
            # elif platform == "gitlab":
            #     issue_url = gitlab.create_issue(repo_url, title, body)
            else:
                raise ValueError(f"Unsupported platform: {platform}")

            click.echo(f"  ✓ Issue created: {issue_url}")

            created.append(
                {
                    "repo_url": repo_url,
                    "issue_url": issue_url,
                    "platform": platform,
                    "pitfalls_count": len(pitfalls.get_pitfalls_list(data)),
                }
            )

        except Exception as e:
            click.echo(f"  ✗ Error: {e}", err=True)
            failed.append({"file": str(file_path), "error": str(e)})

        click.echo()

    # Save reports
    with open(issues_dir / "created_issues_report.json", "w") as f:
        json.dump(created, f, indent=2)
    click.echo(f"Created issues report: {issues_dir / 'created_issues_report.json'}")

    if failed:
        with open(issues_dir / "failed_issues_report.json", "w") as f:
            json.dump(failed, f, indent=2)
        click.echo(f"Failed issues report: {issues_dir / 'failed_issues_report.json'}")

    # Display summary
    click.echo(f"\n{'=' * 60}")
    click.echo(f"Summary: Created {len(created)} | Failed {len(failed)}")
    click.echo(f"{'=' * 60}\n")

    if failed:
        click.echo(f"⚠️  {len(failed)} issues failed to create.", err=True)
        return 1

    return 0
