"""Issue creation command for sw-metadata-bot."""

import json
from pathlib import Path

import click

from sw_metadata_bot.repo_api import RepoAPI
from sw_metadata_bot.repo_utils import RepoType, get_repo_type
from sw_metadata_bot.utils import create_issue

from .analysis_infos import (
    check_is_pitfall,
    get_analysis_version_info,
    get_date_created,
    get_pitfalls_list,
    get_url_from_pitfalls_data,
    load_pitfalls,
)
from .issue_constants import ISSUE_TITLE, format_issue_body

HOST_REPO_IMPLEMENTED = [RepoType.GITHUB]


def get_current_timestamp() -> str:
    """Get the current timestamp as a formatted string."""
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat() + "Z"


def create_pitfall_element_content_report(pitfall: dict) -> list[str]:
    """Create a markdown report section for a single pitfall or warning."""
    report_lines = []
    is_pitfall = check_is_pitfall(pitfall)
    element_type = "Pitfall" if is_pitfall else "Warning"
    report_lines.append(
        f"## {element_type} ID: {pitfall.get('checkId', 'Unknown ID')}\n"
    )
    report_lines.append(
        f"- **Description**: {pitfall.get('process', 'No description provided')}"
    )
    report_lines.append(
        f"- **Evidence**: {pitfall.get('evidence', 'No evidence provided')}"
    )
    report_lines.append(
        f"- **Suggestion to fix**: {pitfall.get('suggestion', 'No automatic suggestion available.')}"
    )
    return report_lines


def create_suggestion_report_content(repo_url: str, pitfalls_data: dict) -> str:
    """Create a markdown report compiling pitfalls and warnings with suggestions."""

    # retrieve informations from the main dictionary
    analysis_version_info = get_analysis_version_info()
    list_pitfalls = get_pitfalls_list(pitfalls_data)
    date_analysis = get_date_created(pitfalls_data)

    # create report content
    report_lines = [f"# Automated Analysis Report for {repo_url}\n"]
    report_lines.append(f"**date of analysis:** {date_analysis}")
    report_lines.append(
        f"**metacheck version:** {analysis_version_info.get('metacheck_version', 'N/A')}"
    )
    report_lines.append(
        f"**SOMEF version:** {analysis_version_info.get('somef_version', 'N/A')}\n"
    )

    for pitfall in list_pitfalls:
        pitfall_lines = create_pitfall_element_content_report(pitfall)
        report_lines.extend(pitfall_lines)
        report_lines.append("\n---\n")

    return "\n".join(report_lines)


def save_issues_infos(issues_report_file: Path, list_issues_infos: list[dict]) -> None:
    """Save created issues information to a file."""
    with open(issues_report_file, "w", encoding="utf-8") as f:
        json.dump(list_issues_infos, f, indent=4)


@click.command()
@click.option(
    "--pitfalls-output-dir",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    required=True,
    help="Directory containing pitfalls JSON-LD files generated by metacheck.",
)
@click.option(
    "--issues-dir",
    type=click.Path(file_okay=False, dir_okay=True, path_type=Path),
    default=Path.cwd(),
    help="Directory to save created issues report file.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Simulate issue creation without actually creating issues.",
)
def create_all_issues(pitfalls_output_dir: Path, issues_dir: Path, dry_run: bool):
    """Create issues based on metadata analysis results."""

    map_apis: dict[RepoType, RepoAPI] = {}
    list_issues_infos = []
    click.echo(
        f"Creating issues with dry_run={dry_run}, pitfalls_output={pitfalls_output_dir}"
    )
    issues_dir.mkdir(parents=True, exist_ok=True)

    # list the number of repos analyzed from the pitfalls_output file
    if pitfalls_output_dir:
        pitfalls_files = list(Path(pitfalls_output_dir).glob("*.jsonld"))
        click.echo(
            f"Found {len(pitfalls_files)} pitfalls files in {pitfalls_output_dir}"
        )
    else:
        click.echo("No pitfalls output directory provided.")

    for pitfalls_file in pitfalls_files:
        click.echo(f"Processing pitfalls file: {pitfalls_file}")

        # Load pitfalls data
        pitfalls_data = load_pitfalls(pitfalls_file)

        # Extract repository URL
        repo_url = get_url_from_pitfalls_data(pitfalls_data)
        repo_type = get_repo_type(repo_url)
        click.echo(f"Repository URL: {repo_url}")

        # Create report content
        report_content = create_suggestion_report_content(repo_url, pitfalls_data)

        # Format issue body
        issue_title = ISSUE_TITLE
        issue_body = format_issue_body(report_content)

        # save issue body to a file for reference
        issue_body_file = issues_dir / f"issue_body_{pitfalls_file.stem}.md"
        with open(issue_body_file, "w", encoding="utf-8") as f:
            f.write(issue_body)
        click.echo(f"Issue body saved to {issue_body_file}")

        # Create issue using the appropriate API
        if repo_type not in HOST_REPO_IMPLEMENTED:
            click.echo(
                f"Repository host {repo_type} not supported for issue creation. Skipping."
            )
            continue
        if repo_type not in map_apis:
            if repo_type == RepoType.GITHUB:
                from .github_api import GitHubAPI

                api_instance = GitHubAPI(dry_run=dry_run)
            else:
                click.echo(
                    f"Repository host {repo_type} not supported for issue creation. Skipping."
                )
                continue
            map_apis[repo_type] = api_instance
        issue_url = create_issue(map_apis[repo_type], repo_url, issue_title, issue_body)
        issue_timestamp_created = get_current_timestamp()
        issue_infos = {
            "repo_url": repo_url,
            "issue_url": issue_url,
            "dry_run": dry_run,
            "date_created": issue_timestamp_created,
        }
        list_issues_infos.append(issue_infos)

    # save created issues information to a file
    issues_report_file = issues_dir / "created_issues_report.json"
    save_issues_infos(issues_report_file, list_issues_infos)
    click.echo(f"Created issues report saved to {issues_report_file}")
