"""Issue reporting and formatting utilities."""

from datetime import datetime, timezone
from typing import Optional

from ..core.pitfalls_analyzer import PitfallsAnalyzer


class ReportFormatter:
    """Formats pitfalls data and analysis into issue content."""

    @staticmethod
    def format_check_item(check: dict, is_pitfall: bool) -> str:
        """
        Format a single check (pitfall or warning) as markdown.

        Args:
            check: Check/pitfall dictionary from pitfalls data
            is_pitfall: True if this is a pitfall, False if warning

        Returns:
            Formatted markdown string
        """
        element_type = "🔴 Pitfall" if is_pitfall else "⚠️ Warning"
        check_id = check.get("checkId", "Unknown")
        description = check.get("process", "No description")
        evidence = check.get("evidence", "No evidence provided")
        suggestion = check.get("suggestion", "No automatic suggestion available.")

        return f"""
### {element_type}: {check_id}

- **Description**: {description}
- **Evidence**: {evidence}
- **Suggestion to fix**: {suggestion}
"""

    @staticmethod
    def format_pitfalls_report(
        repo_url: str,
        pitfalls_data: dict,
        custom_template: Optional[str] = None,
    ) -> str:
        """
        Generate a markdown report from pitfalls data.

        Args:
            repo_url: The repository URL being analyzed
            pitfalls_data: The pitfalls analysis data
            custom_template: Optional custom template (not used here, for future extensibility)

        Returns:
            Formatted markdown report
        """
        analyzer = PitfallsAnalyzer()

        # Extract information
        version_info = analyzer.get_version_info()
        date_created = analyzer.get_date_created(pitfalls_data)
        pitfalls, warnings = analyzer.classify_checks(pitfalls_data)

        # Build report
        lines = [
            "# Automated Metadata Analysis Report",
            "",
            f"**Repository**: {repo_url}",
            f"**Analysis Date**: {date_created}",
            f"**MetaCheck Version**: {version_info.get('metacheck_version', 'N/A')}",
            f"**SOMEF Version**: {version_info.get('somef_version', 'N/A')}",
            "",
            "## Summary",
            f"- **Total Pitfalls**: {len(pitfalls)}",
            f"- **Total Warnings**: {len(warnings)}",
            "",
        ]

        if pitfalls:
            lines.append("## Pitfalls")
            lines.append("")
            for pitfall in pitfalls:
                lines.append(
                    ReportFormatter.format_check_item(pitfall, is_pitfall=True)
                )
            lines.append("")

        if warnings:
            lines.append("## Warnings")
            lines.append("")
            for warning in warnings:
                lines.append(
                    ReportFormatter.format_check_item(warning, is_pitfall=False)
                )
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def get_current_timestamp() -> str:
        """Get current timestamp in ISO format."""
        return datetime.now(timezone.utc).isoformat() + "Z"


class IssueTemplate:
    """Standard issue templates for different platforms."""

    @staticmethod
    def create_issue_body(report_content: str) -> str:
        """
        Create a complete issue body with template.

        Args:
            report_content: The formatted analysis report

        Returns:
            Complete issue body for posting
        """
        template = """Hi maintainers,

Your repository is part of our metadata quality improvement initiative. We've automatically analyzed your repository's metadata and discovered some issues that could be fixed.

This automated issue includes:
- Detected metadata pitfalls and warnings
- Suggestions for fixing each issue

## Context

This analysis is performed by the [CodeMetaSoft](https://w3id.org/codemetasoft) project to help improve research software quality.

If you're not interested in participating, you can comment "unsubscribe" and we'll remove your repository from our list.

---

{report_content}

---

### About this report

This is an automated report generated by the SW Metadata Bot tool using RSMetaCheck analysis. For more information, visit:
- [CodeMetaSoft Project](https://w3id.org/codemetasoft)
- [RSMetaCheck](https://github.com/SoftwareUnderstanding/RsMetaCheck)
- [SW Metadata Bot](https://github.com/codemetasoft/sw-metadata-bot)
"""
        return template.format(report_content=report_content)
