name: RsMetaCheck Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, labeled, unlabeled] # Needed to catch label changes

env:
  RSMETACHECK_INPUT: "https://github.com/SoftwareUnderstanding/sw-metadata-bot"
  RSMETACHECK_PITFALLS_OUTPUT: "./pitfalls_outputs"
  RSMETACHECK_VERBOSE: "false"
  RSMETACHECK_CONFIG_FILE: "./.github/workflows/rsmetacheck_config.toml"
  RSMETACHECK_ACTION_VERSION: "0.3.2"

jobs:
  analyze-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Determine Environment
        id: check_label
        run: |
          if echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | grep -q "prerelease"; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Run RSMetacheck with unstable config
        if: env.IS_PRERELEASE == 'false'
        uses: SoftwareUnderstanding/rs-metacheck-action@${{ env.RSMETACHECK_ACTION_VERSION }}
        with:
          input: ${{ env.RSMETACHECK_INPUT }}
          branch: $GITHUB_REF
          pitfalls_output: ${{ env.RSMETACHECK_PITFALLS_OUTPUT }}
          verbose: ${{ env.RSMETACHECK_VERBOSE }}
          config_file: ${{ env.RSMETACHECK_CONFIG_FILE }}
          config-profile: "unstable"

      - name: Run RSMetacheck with Release profile
        if: env.IS_PRERELEASE == 'true'
        uses: SoftwareUnderstanding/rs-metacheck-action@${{ env.RSMETACHECK_ACTION_VERSION }}
        with:
          input: ${{ env.RSMETACHECK_INPUT }}
          branch: $GITHUB_REF
          pitfalls_output: ${{ env.RSMETACHECK_PITFALLS_OUTPUT }}
          verbose: ${{ env.RSMETACHECK_VERBOSE }}
          config_file: ${{ env.RSMETACHECK_CONFIG_FILE }}
          config-profile: "release"